// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agfrcauelhojjlehybxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZnJjYXVlbGhvampsZWh5YnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MTcxMTQsImV4cCI6MjA1MjA5MzExNH0.fQclv58Fx5q7BfyYotCDsdbxgTpEqADDQjB8RFtVtmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);